### ISSUE TITLE
Device + SSID does not produce valid PSK candidates

### ISSUE THREAD

**Issue by RealEnder** [jclehner/upc-twg8x0#3]
I did a fast check on this against my captures, using device and SSID as parameters. The results:
Device twg850/UPC%06d:
  Around 200 captures, no valid PSKs. I have only one broken, which is UPC288755 with PSK RMFUWJZG. upc-twg8x0 returns no candidates.
Device twg870/UPC%07d:
 Around 300 captures, no valid PSKs.
Device tc7200/UPC%07d:
 Around 300 captures, no valid PSKs.
I successfully used modified usb_keys.c (see here: https://github.com/RealEnder/routerkeygenPC/blob/master/src/algorithms/Upc07Keygen.cpp) to break other UPC%07d handshakes.
Will be happy to test again or help with re process.

**Comment by jclehner** [comment]
`UPC%07d` networks can be from TC7200s or TWG870s, but the algo is very different. TWG870 SSIDs can be distinguished from others by two leading zeroes, and the remaining five digits in the range of `30000` to `60000`.

The `tc7200` device is a test, because the mechanism from `upc_keys.c` (and your program) does work with most, but not all TC7200s (and it doesn't on mine). I'm in the process of reverse engineering the firmware, and so far I've discovered that the 5.0 GHz SSID on my TC7200.U is generated by the same algo as on the TWG870 (but the algo used to transform the `XXXXNNNNNNNN` serial number to an `int[5]` is different).

It's possible that the 300 `UPC%07d` handshakes use the same algo as my TC7200.U, and are not from TWG870s (in my city, the TWG870 is a much rarer occurence than the TC7200.U, and the TWG850 even more so). Or, they are from a TWG870 with a serial prefix other than `00955` (I haven't found one yet).

As for the 200 `UPC%06d` handshakes, I'm not sure. I've verified the algo for around 10 different TWG850s, and all (known) prefixes (`00913`, `00926`, `00939`), but it's possible that there are more. Also, most TWG850 networks I've found have one leading zero, i.e. `UPC0xxxxx`.

Some BSSIDs from the `UPC%06d` and `UPC%07d` would be helpful.

**Comment by RealEnder** [comment]
All my UPC00ddddd are uncracked (~140) and their BSSIDs are with those OUIs:
00:26:24, 24:ec:99(this can be false), 28:be:9b, 44:d8:84 (maybe false also), 80:c6:ab, c0:4a:00 (may be false also) and fc:94:e3. By "false" I mean I have only one capture.
Some BSSID + SSIDs:

```
00:26:24:1c:ac:85   UPC0045405
28:be:9b:04:ae:1b   UPC0047761
80:c6:ab:08:62:04   UPC0049099
8c:04:ff:01:ea:61   UPC0050605
fc:94:e3:02:5b:fe   UPC0051394
```

As of UPC0ddddd:
OUIs: 00:18:9b, 00:1e:69, 00:24:d1, 38:60:77, 4c:72:b9, 70:54:d2, 70:71:bc, e0:69:95, e8:40:f2
Some BSSID + SSIDs:

```
00:18:9b:6f:15:08   UPC016635
00:1e:69:61:af:b9   UPC008331
00:24:d1:70:af:14   UPC009197
38:60:77:c2:fc:47   UPC055589
70:54:d2:a7:af:6a   UPC076214
70:71:bc:00:1a:a9   UPC012396
e0:69:95:78:8b:f2   UPC052557
```

You may find those searching here: http://wpa-sec.stanev.org
You can sear by SSID (accepting % and _ for wildcards), or OUI
Also wigle.net (https://www.wigle.net/search) will give you much more.

**Comment by RealEnder** [comment]
Well, this was embarrassing.
At last I found some time to reverse the TC7200.20 firmware again and of course confirmed the algos.
Then checked the code I used to compare the results from the generator against those in the wpa-sec and uncracked handshakes/PMKIDs. I've incidentally added a single space after each candidate in the wordlist and of course this gave me zero founds.
Just for info, the algo is added to my branch of RouterKeygenPC and will shortly be committed upstream.
The other algos in the image still need to be reversed, a lot of stuff there. Hope this will not get me another 4 years :)
Thanks for your work and sorry for the misleading issue.
